# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b87eef80fd7ca35ba10b3af4bb8a0564319387a1fbaa22ec6153a54471b17d331b4500477c0a217477343cc36ac5126564e98207f06b1000a6b08a5332f9b2ab

test:
  secret_key_base: 3680ce72bdae922780b0a4e9575134a86b22610b6e8cce583c6fc35a386bab5d6817c4b8c4dfa6b2b6a24ff842e792002330a1065b58c0cc66f240a6aa9081ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
